[custom]
;大陆白名单模式，无污染，无泄漏，降低延迟提升响应速度！

;设置规则标志位
ruleset=⛔️ 不走代理,https://raw.githubusercontent.com/MIT-X/CS/main/Ruleset/LocalAreaNetwork.list
ruleset=📲 电报信息,https://raw.githubusercontent.com/MIT-X/CS/main/Ruleset/Telegram.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/MIT-X/CS/main/Ruleset/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/MIT-X/CS/main/Ruleset/Apple.list
ruleset=🌎 谷歌服务,https://raw.githubusercontent.com/MIT-X/CS/main/Ruleset/YouTube.list
ruleset=🌎 谷歌服务,https://raw.githubusercontent.com/MIT-X/CS/main/Ruleset/Google.list
ruleset=⛔️ 不走代理,https://raw.githubusercontent.com/MIT-X/CS/main/Ruleset/UnBan.list
ruleset=⛔️ 不走代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=⛔️ 不走代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=⛔️ 不走代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=⛔️ 不走代理,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=⛔️ 不走代理,[]GEOIP,CN,no-resolve
ruleset=🚀 科学上网,[]FINAL

;设置分组标志位
custom_proxy_group=🚀 科学上网`select`.*
custom_proxy_group=🌎 谷歌服务`select`.*`[]DIRECT
custom_proxy_group=Ⓜ️ 微软服务`select`.*`[]DIRECT
custom_proxy_group=📲 电报信息`select`.*`[]DIRECT
custom_proxy_group=💰 加密货币`select`.*`[]DIRECT
custom_proxy_group=🍎 苹果服务`select`.*`[]DIRECT
custom_proxy_group=⛔️ 不走代理`select`[]DIRECT

enable_rule_generator=true
overwrite_original_rules=true